name: 'Mirror'
on:
  push:
    branches:
      - main
jobs:
  Mirror-action:
    runs-on: ubuntu-20.04
    steps:
      - name: MirrorV2
        uses: tmfg/digitraffic-actions@mirror/v2
        with:
          mirror-repo: git@github.com:mattihe/mirror-action-testing.git
          ssh-private-key: ${{ secrets.SSH_MIRROR_KEY }}
          refspec: main

