name: 'Mirror'
#on:
#  push:
#    branches:
#      - master
jobs:
  Mirror-action:
    runs-on: ubuntu-20.04
    steps:
      - name: MirrorV2
        uses: tmfg/digitraffic-actions@mirror/v2
        with:
          mirror-repo: git@github.com:mattihe/mirror-action-v2-test.git
          ssh-private-key: ${{ secrets.SSH_MIRROR_KEY }}

